notifications:
  email: false
language: python
python:
  - "3.9"
# command to install dependencies
before_install:
- pip install poetry
install:
- poetry install -v
# command to run tests
script: pytest
